# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: To be decided 
    url: tour
    weight: 10
  - name: To be decided 
    url: post
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: To be decided 
    url: event
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: To be decided 
    url: contact
    weight: 60
